name: Manual Workflow Trigger

on: [workflow_dispatch]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update configs
      run:  ./depdends.sh
    - name: Docker Build
      run: docker build -t gluster-build .
    - name: Docker running
      run: docker run --name container_gluster gluster-build
    - name: Copy Artifactory to Host
      run: docker cp container_gluster:/github/TEST_G/extras/LinuxRPM .
    - name: Upload Artifactory
      uses: actions/upload-artifact@v2
      with:
          name: gluster-rpms
          path: LinuxRPM/*.rpm
