name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./depdends.sh
    - name: configure
      run:  ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
