name: Manual Workflow Trigger
on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup
      run: ./depdends.sh
    - name: Docker Build
      run: docker build -t gluster-build .
