name: Manual Workflow Trigger

on: [workflow_dispatch]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./depdends.sh
    - name: Docker Build
      run: docker build -t gluster-build .
