name: Gluster Build (centos8:stream/quay)

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             chmod +x setup-os.sh
             chmod +x startscript.sh
             ./Setup_Host.sh
    - name: Pull Docker Image From Quay 
      run: docker pull quay.io/centos/centos:stream8
    - name: Running Build in Centos8 Container
      run: docker run -it -v /$(pwd):/host --name container_gluster quay.io/centos/centos:stream8
    - name: Change to host directory
      run: cd host/
    - name: setup the os dependencies, since container is pulled raw from Quay
      run: ./setup-os.sh
    - name: Run the startup script
      run: ./startscript.sh
    - name: Copy Artifactory to Host
      run: docker cp container_gluster:/glusterfs/extras/LinuxRPM .
    - name: Upload Artifactory
      uses: actions/upload-artifact@v2
      with:
          name: gluster-rpms
          path: LinuxRPM/*.rpm
          retention-days: 1
    - name: Exit the interactive terminal to host
      run: exit
