name: Gluster Build (centos8:stream/quay)

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             chmod +x setup-os.sh
             chmod +x startscript.sh
             ./Setup_Host.sh
    - name: Pull Docker Image From Quay 
      run: docker pull quay.io/centos/centos:stream8
    - name: Running Build in ubuntu Container
      run:  docker run --rm -i --name container_gluster -v /build-out:/out quay.io/centos/centos:stream8 bash
    - name: Copy files to mounted dir
      run: sudo cp setup-os.sh startscript.sh /build-out/
    - name: Copy script to container
      run: cp /out/*.sh .
    - name: setup the os dependencies, since container is pulled raw from Quay
      run: ./setup-os.sh
    - name: Run the startup script
      run: ./startscript.sh
    - name: Exit the interactive terminal to host
      run: exit
