name: Workflow for Codecov Action

on: [workflow_dispatch]

jobs:
 build:
 
      runs-on: ubuntu-latest
      
      steps:
      
         - uses: carlosperate/download-file-action@v1.0.3
         - name: Download a file
           with:
            file-url: 'wget https://build.gluster.org/job/line-coverage/lastSuccessfulBuild/Line_20Coverage_20Report/index.html'
            file-name: 'Line_20Coverage_20Report.html'
            location: './report'
         - name: Print the file path
           run: echo "The file was downloaded to ${{ steps.download-coverage-results.outputs.file-path }}"
         - name: Upload coverage to Codecov
         - uses: codecov/codecov-action@v2
           with:
            files: ./Line_20Coverage_20Report.html
