name: Gluster Build (centos8:stream/quay)

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure Host
      run: |
             chmod +x Setup_Host.sh
             ./Setup_Host.sh
    - name: Pull Docker Image From Quay 
      run: docker pull quay.io/centos/centos:stream8
    - name: Running Build in Centos8 Container
      run: docker run --name container_gluster -v /build-out:/out quay.io/centos/centos:stream8
    - name: Upload Artifactory
      uses: actions/upload-artifact@v2
      with:
          name: gluster-rpms
          path: /build-out/*.*rpm
          retention-days: 1
