name: list-merged-pull-requests example

on:
   workflow_dispatch:
   
jobs:
  example:
    name: Release management comment
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: tiwanari/list-merged-pull-requests@master
        with:
          token: ${{ github.token }}
