name: Quay Monthly Trigger 

on: [workflow_dispatch]

jobs:
  run:
    name: Update a text file
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      # You can make whatever type of change to the repo...
      - run: echo "Quay Build is triggered on $(date)" >> ./Dockerfile/monthly-trigger.txt

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'GitHub Actions Monthly Trigger'
          add: 'monthly-trigger.txt --force'
          cwd: '/Dockerfile/'
          default_author: github_actions
