name: Create Release Build Centos-7 

on: [workflow_dispatch]
  inputs:
    branchnumber:
        description: 'Name of Release(eg 8.3.1)'
        required:true
           

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
    - uses: actions/checkout@v2
    - name: Checkout Release Branch
      run: git checkout -b release-v${{github.event.inputs.branchnumber}}
    - name: Update configs
      run: |
          touch Dockerfile
          cp Dockerfile_centos7 Dockerfile
          ./depdends.sh
    - name: Docker Build
      run: docker build -t gluster-build .
    - name: Docker running
      run: docker run --name container_gluster gluster-build
    - name: Copy Artifactory to Host
      run: docker cp container_gluster:/github/TEST_G/extras/LinuxRPM .
    - name: Upload Artifactory
      uses: actions/upload-artifact@v2
      with:
          name: gluster-rpms
          path: LinuxRPM/*.rpm
          retention-days: 1
