name: Create Release Build  

on: 
  workflow_dispatch:
  
    inputs:
      branchnumber:
        description: 'Release Branch Number (eg v8.3)'
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Release Branch
      with:
        repository: gluster/glusterfs
        path: './glusterfs'
