name: OpenSuse Build 

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - shell: bash
        env: |
            USER: ${{ secrets.SUSE_USER }}
            PASSWORD: ${{ secrets.SUSE_PASSWORD }}
        run: |
         echo "$USER"

      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
             dnf -y install zypper
             sudo zypper in osc

      - name: clone-gluster-suse
        run:  clone-gluster-suse.sh tumbleweed 7 7.3
